config/routes.rb
Crowdrevolt::Application.routes.draw do
  #password reset
  resources :password_resets

  #user sessions
  get "user_session/new"
  get "user_session/create"
  get "user_session/destroy"

# Admin namespace
  namespace :admin do
    # Admin root
    root :to => "channels#index"

    # Inloggen
    get    "inloggen"  => "sessions#new",     :as => :login
    get    "archived"  => "channels#archived",     :as => :archived
    get    "live"  => "episodes#live",     :as => :live
    match '/channels/archive/:id' => "channels#archive", :as => 'archive'
    match '/channels/unarchive/:id' => "channels#unarchive", :as => 'unarchive'
    post   "inloggen" => "sessions#create",  :as => :login
    delete "uitloggen" => "sessions#destroy", :as => :logout

    # Resources
    resources :admins
    resources :contact_questions
    resources :users
    resources :contacts
    resources :texts, :only => [:edit, :update, :index]
    resources :channels do
      resources :posts

      resources :challenges
      resources :episodes do
        resources :questions
      end
    end
    resources :pages
    resources :images
    resources :categories do
      put :sort, :on => :collection  # Sorteren van categorieën
    end
  end

  # Hier komen de publieke resources
  get "page/:id"            => "pages#show",          :as => :page
  get "home"                => "pages#index",         :as => :home
  # get "users"                => "users#solutions",         :as => :user_solutions
  match '/users/:id/solutions', :controller => 'users', :action => 'solutions', :as => :user_solutions
  match '/users/:id/ideas', :controller => 'users', :action => 'ideas', :as => :user_ideas

  get "toggle-edit"         => "application#toggle",  :as => :toggle_edit
  resources :subscribers, :only => :create
  resources :users do
    member do
      get :activate
    end
  end

  resources :messages
  resources :contacts, :only => [:create]
  resources :images, :path => "fotos"
  resources :questions, :path => "kijkersvragen"
  resources :admins, :path => "changemakers"
  resources :channels, :path => "programmas" do
    resources :messages
    resources :challenges, :path => "uitdagingen" do
      resources :solutions, :path => "oplossingen" do
        resources :comments
        resources :appreciables
      end
    end
    resources :episodes, :path => "afleveringen" do
      resources :messages
      resources :questions
    end
    resources :posts, :path => "artikelen", :only => [:index, :show] do
      resources :comments
    end
    resources :ideas, :path => "ideeen" do
      resources :comments
      resources :appreciables
    end
  end

  resources :user_sessions
  resources :posts do
    resources :comments
  end

  # gebruiker Inloggen
  match 'login' => 'user_sessions#new', :as => :login
  post 'available' => 'episodes#available', :as => :available
  get    "inloggen"  => "user_sessions#new",     :as => :user_login

  get    "zoeken"  => "application#search",     :as => :search
  get    "registreren"  => "users#new",     :as => :register
  post   "inloggen" => "user_sessions#create",  :as => :user_login
  get "uitloggen" => "user_sessions#destroy", :as => :user_logout

  get    "about"  => "pages#about",     :as => :about
  get    "karma"  => "pages#karma",     :as => :karma
  get    "contact"  => "pages#contact",     :as => :contact
  get    "faq"  => "pages#faq",     :as => :faq


  # Root pad
  root :to => "channels#index"
end

app/models/image.rb
class Image < ActiveRecord::Base
  # Relations
  has_many :image_relations, :dependent => :destroy


  # Paperclip
  has_attached_file :image, :styles => {
    :original => ["1024>", :jpg],
    :front => ["768x348#", :jpg],
    :thumb => ["120x120#", :jpg]
  }, :url => "/uploads/images/:id/:style.:extension"

  # Validation
  validates_length_of :name, :maximum => 50

  # Paperclip Validation
  include PaperclipValidator
  validates_paperclip_presence :image
  validates_paperclip_content_type :image, :content_type => /image\/jpeg|image\/png|image\/gif|image\/pjpeg|image\/x-png/
  validates_paperclip_size :image, :less_than => 10.megabytes

  # Mass-assignment
  attr_accessible :name, :source, :image, :crop_x, :crop_y, :crop_w, :crop_h, :thumbnail



  # Cropper
  include Cropper

  # Methods
  def image_size(style)
    case style
      when :thumb then width, height = 120, 120
      when :front then width, height = 768, 348
    end
    "#{width}x#{height}#"
  end

  def extract_zip_or_save
    if image?
      self.save
    elsif zip?
      extract_zip
    end
  end

  def image?
    %w(image/jpeg image/png image/gif image/pjpeg image/x-png).include?(image_content_type)
  end

  def zip?
    %w(application/zip).include?(image_content_type)
  end

  def allow_only_images
    return false unless image?
  end

  def extract_zip
    dir = Dir.mktmpdir
    begin
      Archive::Zip.extract(image.queued_for_write[:original].path, dir)

      Dir.entries(dir).each do |entry|
        next if !entry.match(/\.jpg|\.jpeg|\.gif|\.png$/i)
        Image.create(:image => File.open(File.join(dir, entry)), :name => name)
      end

      true
    rescue
      false
    ensure
      FileUtils.remove_entry_secure(dir)
      GC.start
    end
  end

  def url(style)
    image.url(style)
  end
end

app/controllers/admin/images_controller.rb
class Admin::ImagesController < AdminController
  before_filter :find_image, :only => [:edit, :update, :destroy]

  def index
    @images = Image.where(:user_id => nil).order("id DESC")
    @images = @images.search(:name_or_tag_taggings_tag_name_contains => params[:q]) if params[:q].present?
    @images = @images.page(params[:page]).per_page(params[:total].try(:to_i) || 40)
  end

  def new
    @image = Image.new
  end



  def create
    @image = Image.new(params[:image])
    if @image.extract_zip_or_save
      respond_to do |format|
        format.js
        format.html { redirect_to([:admin, :images], :flash => :success) }
      end
    else
      flash_now!(:error)
      render("new")
    end
  end

  def edit
    @image.thumbnail = params[:crop]
  end

  def update
    if @image.update_attributes(params[:image])
      redirect_to([:edit, :admin, @image], :flash => :success)
    else
      raise
      flash_now!(:error)
      render("edit")
    end
  end

  def destroy
    @image.destroy
    redirect_to([:admin, :images], :flash => :success)
  end

private

  def find_image
    @image = Image.find(params[:id])
  end
end

app/controllers/images_controller.rb
class ImagesController < ApplicationController
  before_filter :find_image, :only => [:edit, :update, :destroy]

  def index
    @images = Image.where(:user_id => current_user.id).order("id DESC")
    @images = @images.search(:name_or_tag_taggings_tag_name_contains => params[:q]) if params[:q].present?
    @images = @images.page(params[:page]).per_page(params[:total].try(:to_i) || 40)
  end

  def new
    @image = Image.new
    respond_to do |format|
        format.js
        format.html { redirect_to([:new, @image], :flash => :success) }
      end
  end



  def create
    @image = Image.new(params[:image])
    @image.user_id = current_user.id
    if @image.extract_zip_or_save
      respond_to do |format|
        format.js
        format.html { redirect_to([:admin, :images], :flash => :success) }
      end
    else
      flash_now!(:error)
      render("new")
    end
  end

  # def edit
  #   @image.thumbnail = params[:crop]
  # end

  # def update
  #   if @image.update_attributes(params[:image])
  #     redirect_to([:edit, :admin, @image], :flash => :success)
  #   else
  #     raise
  #     flash_now!(:error)
  #     render("edit")
  #   end
  # end

  def destroy
    @image.destroy
    redirect_to([:admin, :images], :flash => :success)
  end

private

  def find_image
    @image = Image.find(params[:id])
  end
end

app/helpers/admin/images_helper.rb
module Admin::ImagesHelper
  def cropped_image(image)
    image_tag(image.image.url, :id => "Jcrop", :data => {
      :ratio => image.ratio(params[:crop]),
      :min_w => image.min_w(params[:crop]),
      :min_h => image.min_h(params[:crop])
    })
  end

  # Image image crop tag
  def image_thumb(image, thumb, *args)
    options = args.extract_options!
    options[:width], options[:height] = image.image_size(thumb).match(/(\d*)x(.\d*)/).captures if options[:width].blank? && options[:height].blank?
    image_tag(image.image.url(thumb), options)
  end

  # Pagination for image
  def paginate_images(images)
    will_paginate(images, :params => { :controller => "admin/images", :action => "index" })
  end
end

app/views/admin/images/_form.html.haml
- if request.xhr?
  %ul.breadcrumb
    %li
      = link_to t("admin.images.crumb").html_safe, admin_images_path(:total => 15), :remote => true, :class => "image_ajax"
      %span.divider /
    %li= t("admin.images.new")

= simple_form_for [:admin, @image], :html => { :multipart => true, :class => request.xhr? ? "image_ajax form-horizontal" : "form-horizontal" }, :remote => request.xhr? do |f|
  - if !@image.new_record? && params[:crop]
    = cropped_image(@image)
    = f.hidden_field :thumbnail
    = f.hidden_field :crop_x, :id => "crop_x"
    = f.hidden_field :crop_y, :id => "crop_y"
    = f.hidden_field :crop_w, :id => "crop_w"
    = f.hidden_field :crop_h, :id => "crop_h"

    .cropper_submit.mt10
      = f.submit t("admin.images.crop"), :class => "btn btn-primary"
      %span.or= t("admin.or")
      = cancel_link([:edit, :admin, @image])

  - else
    %table.simple_form.mt10
      = f.input :name, :input_html => { :maxlength => 50 }
      / = f.input :tag_list, :as => :tags && !request.xhr?
      = f.input :image, :required => @image.new_record? do
        = f.file_field :image
        - if !@image.new_record? && @image.image_file_name?
          .example_image
            %h3= t("admin.images.page")
            = link_to(image_thumb(@image, :front), edit_admin_image_path(@image, :crop => :front), :class => "crop_thumbs")
      .pull-left.mt10
        = f.submit :class => "btn btn-primary"
        - unless request.xhr?
          %span.or= t("admin.or")
          = link_to t("admin.buttons.terug_overzicht"), [:admin, :images]
          - if !@image.new_record?
            %span.or= t("admin.or")
            = delete_link(@image, :class => "btn btn-danger")

app/views/admin/images/_image.html.haml
= link_to(image_thumb(image, :thumb), [:edit, :admin, image], :remote => request.xhr?, :class => "thumbnail")

app/views/admin/images/_select.html.haml
= f.input :image_select, :wrapper_html => { :class => "image_selector_wrapper" } do
  = f.hidden_field :image_select, :class => "image_selector_field", :data => { :total => total }
  .image_selector= link_to t("admin.images.select"), "#", :class => "image_selector_link image_ajax btn"
  .image_previews
    - f.object.images.each do |image|
      %a.image_preview.thumbnail
        = image_thumb(image, :thumb, :data => { :id => image.id })
        %span.delete X

app/views/admin/images/_selectimages.html.haml
%h2 Selecteer een afbeelding
- @images.each do |image|
  = link_to image_thumb(image, :thumb), "#", :class => "image_selector_add btn thumbnail", :data => { :id => image.id, :url => image.image.url(:thumb), :width => image.min_w(:thumb), :height => image.min_h(:thumb), :text => t("admin.images.added") }

app/views/admin/images/_show.html.haml
%ul.breadcrumb
  %li
    = link_to t("admin.images.crumb").html_safe, admin_images_path(:total => 15), :remote => true, :class => "image_ajax"
    %span.divider /
  %li= @image.name

%table#image_table
  %tr
    %td#image_add
      = link_to image_thumb(@image, :thumb), [:edit, :admin, @image], :class => "thumbnail"
      = link_to t("admin.images.add"), "#", :class => "image_selector_add btn", :data => { :id => @image.id, :url => @image.image.url(:thumb), :width => @image.min_w(:thumb), :height => @image.min_h(:thumb), :text => t("admin.images.added") }
    / %td
    /   %table.table.table-striped.table-bordered
    /     %tr
    /       %th= t("admin.images.original")
    /       %td= text_field_tag :url_original, @image.image.url
    /     %tr
    /       %th= t("admin.images.thumb")
    /       %td= text_field_tag :url_thumb, @image.image.url(:thumb)
    /     %tr
    /       %th= t("admin.images.front")
    /       %td= text_field_tag :url_front, @image.image.url(:front)

app/views/admin/images/create.js.haml
:plain
  $.getScript("#{admin_images_path(:total => 15)}");

app/views/admin/images/edit.html.haml
= link_to t('back'), params[:crop] ? [:edit, :admin, @image] : [:admin, :images], :class => 'btn back'
.page-header
  %h1 Afbeelding
= render("form")

app/views/admin/images/edit.js.haml
:plain
  $("#image_wrapper").show();
  $("#image_wrapper").html("#{j(render("show"))}");
  $("#image_loading").html("");
  $("#image_paginate").html("");

app/views/admin/images/index.html.haml
- model_class = Image
.page-header
  %h1=t '.title', :default => model_class.model_name.human.pluralize
=link_to "Afbeelding uploaden", [:new, :admin, :image], :class => "btn btn-primary"

/= form_tag [:admin, :images], :class => "well form-search input-append", :method => :get do
/ = text_field_tag(:q, params[:q], :placeholder => t("admin.search_term"), :class => "span3 search-query") + submit_tag(t("admin.search"), :class => "btn")


#images= render @images

#image_pagination= will_paginate @images

app/views/admin/images/index.js.haml
:plain
  $("#image_wrapper").show();
  $("#image_wrapper").html("#{j(render("selectimages"))}");
  $("#image_loading").html("");
  $("#image_paginate").html('#{j(paginate_images(@images))}');
  $("#image_paginate a").attr("data-remote", "true");
  $("#flash_messages").html("#{j(flash_messages(:close))}");

app/views/admin/images/new.html.haml
= link_to t("admin.buttons.terug_overzicht") [:admin, :images]


= render("form")

app/views/admin/images/new.js.haml
:plain
  $("#image_wrapper").show();
  $("#image_wrapper").html("#{j(render("form"))}");
  $("#image_paginate").html("");
  $("#image_loading").html("");
  $("#flash_messages").html("#{j(flash_messages(:close))}");