config/routes.rb
Crowdrevolt::Application.routes.draw do
  #password reset
  resources :password_resets

  #user sessions
  get "user_session/new"
  get "user_session/create"
  get "user_session/destroy"

# Admin namespace
  namespace :admin do
    # Admin root
    root :to => "channels#index"

    # Inloggen
    get    "inloggen"  => "sessions#new",     :as => :login
    get    "archived"  => "channels#archived",     :as => :archived
    get    "live"  => "episodes#live",     :as => :live
    match '/channels/archive/:id' => "channels#archive", :as => 'archive'
    match '/channels/unarchive/:id' => "channels#unarchive", :as => 'unarchive'
    post   "inloggen" => "sessions#create",  :as => :login
    delete "uitloggen" => "sessions#destroy", :as => :logout

    # Resources
    resources :admins
    resources :contact_questions
    resources :users
    resources :contacts
    resources :texts, :only => [:edit, :update, :index]
    resources :channels do
      resources :posts

      resources :challenges
      resources :episodes do
        resources :questions
      end
    end
    resources :pages
    resources :images
    resources :categories do
      put :sort, :on => :collection  # Sorteren van categorieën
    end
  end

  # Hier komen de publieke resources
  get "page/:id"            => "pages#show",          :as => :page
  get "home"                => "pages#index",         :as => :home
  # get "users"                => "users#solutions",         :as => :user_solutions
  match '/users/:id/solutions', :controller => 'users', :action => 'solutions', :as => :user_solutions
  match '/users/:id/ideas', :controller => 'users', :action => 'ideas', :as => :user_ideas

  get "toggle-edit"         => "application#toggle",  :as => :toggle_edit
  resources :subscribers, :only => :create
  resources :users do
    member do
      get :activate
    end
  end

  resources :messages
  resources :contacts, :only => [:create]
  resources :images, :path => "fotos"
  resources :questions, :path => "kijkersvragen"
  resources :admins, :path => "changemakers"
  resources :channels, :path => "programmas" do
    resources :messages
    resources :challenges, :path => "uitdagingen" do
      resources :solutions, :path => "oplossingen" do
        resources :comments
        resources :appreciables
      end
    end
    resources :episodes, :path => "afleveringen" do
      resources :messages
      resources :questions
    end
    resources :posts, :path => "artikelen", :only => [:index, :show] do
      resources :comments
    end
    resources :ideas, :path => "ideeen" do
      resources :comments
      resources :appreciables
    end
  end

  resources :user_sessions
  resources :posts do
    resources :comments
  end

  # gebruiker Inloggen
  match 'login' => 'user_sessions#new', :as => :login
  post 'available' => 'episodes#available', :as => :available
  get    "inloggen"  => "user_sessions#new",     :as => :user_login

  get    "zoeken"  => "application#search",     :as => :search
  get    "registreren"  => "users#new",     :as => :register
  post   "inloggen" => "user_sessions#create",  :as => :user_login
  get "uitloggen" => "user_sessions#destroy", :as => :user_logout

  get    "about"  => "pages#about",     :as => :about
  get    "karma"  => "pages#karma",     :as => :karma
  get    "contact"  => "pages#contact",     :as => :contact
  get    "faq"  => "pages#faq",     :as => :faq


  # Root pad
  root :to => "channels#index"
end

app/models/user.rb
class User < ActiveRecord::Base
  authenticates_with_sorcery!
  attr_accessible :crypted_password, :email, :salt, :username, :password, :password_confirmation, :active, :skypename, :show_skype, :activation_state, :avatar, :optin, :bio, :name
  has_attached_file :avatar, :styles => {
    :portrait => ["300x300#", :jpg],
  }, :url => "/uploads/avatars/:id/:style.:extension"

  #validatie
  validates_presence_of :username, :avatar, :email, :password
  validates_length_of :password, :minimum => 3, :message => "Je wachtwoord moet minstens 6 karakters lang zijn"
  validates_confirmation_of :password, :message => "Je bevestiging was niet gelijk aan je ingevulde wachtwoord"
  validates_uniqueness_of :email, :on => :create
  validates_uniqueness_of :username, :on => :create, :message => "Deze gebruikersnaam is al in gebruik"




  # has_many :posts
  has_many :ideas
  has_many :solutions
  has_many :rewards
  has_many :messages, :as => :author
  has_many :questions
  has_many :comments, :dependent => :destroy
  has_many :appreciables

  def to_param
    "#{id}-#{username}".parameterize
  end
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < AdminController

  def index
    @users = User.all
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    # raise params[:user][:avatar].inspect

      if @user.update_attributes(params[:user])
        redirect_to [:admin, :users], :notice => 'User was successfully updated.'
      else
        render :action => "edit"
      end
  end

  def destroy
    @user = User.find(params[:id])
    @user.destroy
    redirect_to [:admin, :users], :notice => 'User was successfully deleted.'
  end

  # def update
  #   @user = User.find(params[:id])
  #   if @user.update_attributes

  #   end
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  skip_before_filter :require_login, :only => [:index, :new, :create, :activate, :show]

  def index
    @users = User.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render :json => @users }
    end
  end

  def show
    @user = User.find(params[:id])
    @solutions = Solution.find(:all, :limit => 3, :conditions => {:user_id => @user.id})
    @ideas = Idea.find(:all, :limit => 3, :conditions => {:user_id => @user.id})
  end

  def solutions
    @user = User.find(params[:id])
    @solutions = Solution.where(:user_id => @user.id).paginate(:page => params[:page], :per_page => 6)
  end

  def ideas
    @user = User.find(params[:id])
    @ideas = Idea.where(:user_id => @user.id).paginate(:page => params[:page], :per_page => 6)
  end

  def new
    @user = User.new
  end

  def edit
    @user = User.find(params[:id])
  end

  def create
    @user = User.new(params[:user])
    if @user.save
      redirect_to :karma, :notice => 'User was successfully created.'
    else
      render :action => "new"
    end
  end

  def update
    @user = User.find(params[:id])
    # raise params[:user][:avatar].inspect

      if @user.update_attributes(params[:user])
        redirect_to @user, :notice => 'User was successfully updated.'
      else
        render :action => "edit"
      end
  end

  def destroy
    @user = User.find(params[:id])
    @user.destroy

    respond_to do |format|
      format.html { redirect_to users_url }
      format.json { head :no_content }
    end
  end

  def activate
    if (@user = User.load_from_activation_token(params[:id]))
      @user.activate!
      redirect_to(:user_login, :notice => 'User was successfully activated.')
    else
      not_authenticated
    end
  end
end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/admin/users/_form.html.haml
= link_to t("back"), [:admin, :users], :class => 'btn back'
.page-header
  - if @user
    %h1= @user.username
  - else
    %h1= t('admin.users')

= simple_form_for [:admin, @user] do |f|
  -if @user.errors.any?
    #error_explanation
      %h2= "#{pluralize(@user.errors.count, "error")} prohibited this user from being saved:"
      %ul
        - @user.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.input :username, :input_html => { :class => "makeitbig"}
  .field
    = f.input :email, :input_html => { :class => "makeitbig"}
  .field
    = f.file_field :avatar, :input_html => {:class => "btn imgselector", :style => "display:block"}
    / .input-append
    /   =text_field "photoCover", "", :input_html => {:class => "input-large"}
    /   %a.btn{:onclick => "$('input[id=user_avatar]').click()"}= t("select")
  .field
    = f.input :skypename
    = f.input :show_skype
  .field
    = f.input :password
    = f.input :password_confirmation
  .field
    =f.input :bio, :input_html => {:rows => 10}
  .field
    =f.input :optin

  .actions
    = f.submit 'Save', :class => "btn btn-primary"

:javascript
  $("input[id=user_avatar]").change(function(){
  $("#photoCover_").val($(this).val());
  });

app/views/admin/users/edit.html.haml
= render 'form'



app/views/admin/users/index.html.haml
- model_class = User
.page-header
  %h1=t '.title', :default => model_class.model_name.human.pluralize
%table.table
  %thead
    %tr
      %th= model_class.human_attribute_name(:id)
      %th= model_class.human_attribute_name(:email)
      %th= model_class.human_attribute_name(:username)
      %th= model_class.human_attribute_name(:activation_state)
      %th= model_class.human_attribute_name(:optin)
      %th= model_class.human_attribute_name(:skypename)
      %th= model_class.human_attribute_name(:show_skype)
      %th= model_class.human_attribute_name(:created_at)
      %th=t '.actions', :default => t("helpers.actions")
  %tbody
    - @users.each do |user|
      %tr
        %td= link_to user.id, user_path(user)
        %td= user.email
        %td= user.username
        %td= user.activation_state
        %td= user.optin
        %td= user.skypename
        %td= user.show_skype
        %td= user.created_at
        %td
          = link_to t('.edit', :default => t("helpers.links.edit")), [:edit, :admin, user], :class => 'btn btn-mini'
          = link_to t('.destroy', :default => t("helpers.links.destroy")), [:admin, user], :method => :delete, :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, :class => 'btn btn-mini btn-danger'

/ = link_to t('.new', :default => t("helpers.links.new")), [:new, :user], :class => 'btn btn-primary'

app/views/admin/users/new.html.haml
- model_class = User
.page-header
  %h1=t '.title', :default => t('helpers.titles.new', :model => model_class.model_name.human, :default => "New #{model_class.model_name.human}")
= render :partial => "form"

app/views/admin/users/show.html.haml
- model_class = User
.page-header
  %h1=t '.title', :default => model_class.model_name.human

%p
  %strong= model_class.human_attribute_name(:email) + ':'
  %br
  = @user.email
%p
  %strong= model_class.human_attribute_name(:password_digest) + ':'
  %br
  = @user.password_digest
%p
  %strong= model_class.human_attribute_name(:first_name) + ':'
  %br
  = @user.first_name
%p
  %strong= model_class.human_attribute_name(:prefix) + ':'
  %br
  = @user.prefix
%p
  %strong= model_class.human_attribute_name(:last_name) + ':'
  %br
  = @user.last_name
%p
  %strong= model_class.human_attribute_name(:remember_token) + ':'
  %br
  = @user.remember_token
%p
  %strong= model_class.human_attribute_name(:optin) + ':'
  %br
  = @user.optin
%p
  %strong= model_class.human_attribute_name(:accepted) + ':'
  %br
  = @user.accepted
%p
  %strong= model_class.human_attribute_name(:password_reset) + ':'
  %br
  = @user.password_reset

.form-actions
  = link_to t('.back', :default => t("helpers.links.back")), admin_users_path, :class => 'btn'
  = link_to t('.edit', :default => t("helpers.links.edit")), edit_admin_user_path(@user), :class => 'btn'
  = link_to t('.destroy', :default => t("helpers.links.destroy")), admin_user_path(@user), :method => "delete", :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, :class => 'btn btn-danger'